name: Build Resume

on:
  push:
    branches: [main]

jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume-template.tex

      - name: Rename file
        run: mv resume-template.pdf ${{ github.repository_owner }}.pdf

      - name: Commit to master
        uses: EndBug/add-and-commit@v9
        with:
          add: '${{ github.repository_owner }}.pdf'
          message: 'Resume generated and pushed to master'
