name: Build Resume

on:
  push:
    branches: [main]

jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv-gboeing.tex

      - name: Rename file
        run: |
          cv-gboeing.tex ${{ github.repository_owner }}.pdf

      - name: Commit file to master
        uses: EndBug/add-and-commit@v9
        with:
          add: '${{ github.repository_owner }}.pdf'
          message: 'Generated CV'
